//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLC_EXPRESS
{


    public partial class DocumentViewer
    {

        protected global::System.Web.UI.WebControls.Panel DocumentAlertPanel;

        protected global::System.Web.UI.WebControls.Literal DocumentAlertLiteral;

        protected global::System.Web.UI.WebControls.Panel DocumentContentPanel;

        protected global::System.Web.UI.WebControls.Literal DocumentFileNameLiteral;

        protected global::System.Web.UI.WebControls.HyperLink DownloadDocumentHyperLink;

        protected global::System.Web.UI.WebControls.HyperLink BackToCrmHyperLink;

        protected global::System.Web.UI.WebControls.Panel DocumentPreviewAvailablePanel;

        protected global::System.Web.UI.WebControls.Literal DocumentPreviewLiteral;

        protected global::System.Web.UI.WebControls.Panel DocumentPreviewUnavailablePanel;

        protected global::System.Web.UI.WebControls.Panel DocumentAuditEmptyPanel;

        protected global::System.Web.UI.WebControls.Repeater DocumentAuditRepeater;
    }
}
