//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLC_EXPRESS
{


    public partial class Login
    {

        /// <summary>
        /// LoginValidationSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary LoginValidationSummary;

        /// <summary>
        /// ErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;

        /// <summary>
        /// ErrorLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ErrorLiteral;

        /// <summary>
        /// UsernameTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;

        /// <summary>
        /// UsernameRequiredValidator control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator UsernameRequiredValidator;

        /// <summary>
        /// PasswordTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;

        /// <summary>
        /// PasswordRequiredValidator control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator PasswordRequiredValidator;

        /// <summary>
        /// RememberMeCheckBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox RememberMeCheckBox;

        /// <summary>
        /// SignInButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button SignInButton;
    }
}
