//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLC_EXPRESS
{


    public partial class orders
    {

        protected global::System.Web.UI.WebControls.Panel PageAlertPanel;

        protected global::System.Web.UI.WebControls.Literal PageAlertLiteral;

        protected global::System.Web.UI.WebControls.LinkButton DashboardTabButton;

        protected global::System.Web.UI.WebControls.Literal DashboardKpiLiteral;

        protected global::System.Web.UI.WebControls.Literal DashboardInquiryTrendLiteral;

        protected global::System.Web.UI.WebControls.Literal DashboardInquiryStatusLiteral;

        protected global::System.Web.UI.WebControls.Literal DashboardCarBrandLiteral;

        protected global::System.Web.UI.WebControls.Literal DashboardTripTrendLiteral;

        protected global::System.Web.UI.WebControls.Literal TripsFormTitleLiteral;

        protected global::System.Web.UI.WebControls.HiddenField TripsEditingIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox TripsNumberTextBox;

        protected global::System.Web.UI.WebControls.DropDownList TripsClientDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList TripsStatusDropDownList;

        protected global::System.Web.UI.WebControls.TextBox TripsCountryTextBox;

        protected global::System.Web.UI.WebControls.DropDownList TripsVehicleDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList TripsDriverDropDownList;

        protected global::System.Web.UI.WebControls.TextBox TripsStartDateTextBox;

        protected global::System.Web.UI.WebControls.TextBox TripsEndDateTextBox;

        protected global::System.Web.UI.WebControls.TextBox TripsFreightTextBox;

        protected global::System.Web.UI.WebControls.TextBox TripsPrepaymentTextBox;

        protected global::System.Web.UI.WebControls.Button AddTripButton;

        protected global::System.Web.UI.WebControls.Button TripsCancelEditButton;

        protected global::System.Web.UI.WebControls.Button NewTripButton;

        protected global::System.Web.UI.WebControls.HiddenField TripsSelectedIdsHiddenField;

        protected global::System.Web.UI.WebControls.Button TripsBulkEditButton;

        protected global::System.Web.UI.WebControls.Button TripsBulkDeleteButton;

        protected global::System.Web.UI.WebControls.DropDownList TripsBulkStatusDropDownList;

        protected global::System.Web.UI.WebControls.Button TripsBulkStatusButton;

        protected global::System.Web.UI.WebControls.Repeater TripsRepeater;

        protected global::System.Web.UI.WebControls.Panel TripsEmptyPanel;

        protected global::System.Web.UI.WebControls.Literal DriversFormTitleLiteral;

        protected global::System.Web.UI.WebControls.HiddenField DriversEditingIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox DriversFullNameTextBox;

        protected global::System.Web.UI.WebControls.TextBox DriversBirthDateTextBox;

        protected global::System.Web.UI.WebControls.TextBox DriversPhoneTextBox;

        protected global::System.Web.UI.WebControls.TextBox DriversAddressTextBox;

        protected global::System.Web.UI.WebControls.FileUpload DriversPassportUpload;

        protected global::System.Web.UI.WebControls.FileUpload DriversLicenseUpload;

        protected global::System.Web.UI.WebControls.Button AddDriverButton;

        protected global::System.Web.UI.WebControls.Button DriversCancelEditButton;

        protected global::System.Web.UI.WebControls.Button NewDriverButton;

        protected global::System.Web.UI.WebControls.HiddenField DriversSelectedIdsHiddenField;

        protected global::System.Web.UI.WebControls.Button DriversBulkEditButton;

        protected global::System.Web.UI.WebControls.Button DriversBulkDeleteButton;

        protected global::System.Web.UI.WebControls.Repeater DriversRepeater;

        protected global::System.Web.UI.WebControls.Panel DriversEmptyPanel;

        protected global::System.Web.UI.WebControls.Literal FleetFormTitleLiteral;

        protected global::System.Web.UI.WebControls.HiddenField FleetEditingIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox FleetCarBrandTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetCarModelTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetLicensePlateTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetVinTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetTrailerBrandTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetTrailerModelTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetTrailerLicensePlateTextBox;

        protected global::System.Web.UI.WebControls.CheckBoxList FleetDriversCheckBoxList;

        protected global::System.Web.UI.WebControls.FileUpload FleetDocumentsUpload;

        protected global::System.Web.UI.WebControls.Button AddFleetButton;

        protected global::System.Web.UI.WebControls.Button FleetCancelEditButton;

        protected global::System.Web.UI.WebControls.Button NewFleetButton;

        protected global::System.Web.UI.WebControls.HiddenField FleetSelectedIdsHiddenField;

        protected global::System.Web.UI.WebControls.Button FleetBulkEditButton;

        protected global::System.Web.UI.WebControls.Button FleetBulkDeleteButton;

        protected global::System.Web.UI.WebControls.Repeater FleetRepeater;

        protected global::System.Web.UI.WebControls.Panel FleetEmptyPanel;

        protected global::System.Web.UI.WebControls.HiddenField CarsSelectedIdsHiddenField;

        protected global::System.Web.UI.WebControls.DropDownList CarsBulkTripDropDownList;

        protected global::System.Web.UI.WebControls.Button CarsBulkAssignTripButton;

        protected global::System.Web.UI.WebControls.Repeater CarsRepeater;

        protected global::System.Web.UI.WebControls.Panel CarsEmptyPanel;

        protected global::System.Web.UI.WebControls.Literal DashboardCarsFilterNoticeLiteral;

        protected global::System.Web.UI.WebControls.Panel CarsDetailPanel;

        protected global::System.Web.UI.WebControls.LinkButton CloseCarsDetailButton;

        protected global::System.Web.UI.WebControls.Literal CarsDetailTitleLiteral;

        protected global::System.Web.UI.WebControls.Literal CarsDetailMetaLiteral;

        protected global::System.Web.UI.WebControls.DropDownList CarsDetailTripDropDownList;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailForwarderTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailDealerTextBox;

        protected global::System.Web.UI.WebControls.Literal CarsDealerSuggestionsLiteral;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailStatusTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailStartPriceTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailInvoiceTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailYearTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailBrandTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailModelTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailVinTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailLocationTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailTitleTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailKeyTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailInspectionTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailReExportTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailVolumeTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailPowerTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailPortCostTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailLoadingCostTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailTowTruckCostTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailParkingCostTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailInspectionCostTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailReExportCostTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailExpertiseCostTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailDeliveryCostTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailFirstNameTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailLastNameTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailPassportTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailAddressTextBox;

        protected global::System.Web.UI.WebControls.TextBox CarsDetailCommentTextBox;

        protected global::System.Web.UI.WebControls.Button SaveCarsDetailButton;

        protected global::System.Web.UI.WebControls.Literal CarsDetailHistoryLiteral;

        protected global::System.Web.UI.WebControls.Literal ClientsFormTitleLiteral;

        protected global::System.Web.UI.WebControls.HiddenField ClientsEditingIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox ClientsNameTextBox;

        protected global::System.Web.UI.WebControls.TextBox ClientsDirectionTextBox;

        protected global::System.Web.UI.WebControls.TextBox ClientsManagerTextBox;

        protected global::System.Web.UI.WebControls.TextBox ClientsPhoneTextBox;

        protected global::System.Web.UI.WebControls.TextBox ClientsEmailTextBox;

        protected global::System.Web.UI.WebControls.Button AddClientButton;

        protected global::System.Web.UI.WebControls.Button ClientsCancelEditButton;

        protected global::System.Web.UI.WebControls.Button NewClientButton;

        protected global::System.Web.UI.WebControls.HiddenField ClientsSelectedIdsHiddenField;

        protected global::System.Web.UI.WebControls.Button ClientsBulkEditButton;

        protected global::System.Web.UI.WebControls.Button ClientsBulkDeleteButton;

        protected global::System.Web.UI.WebControls.Repeater ClientsRepeater;

        protected global::System.Web.UI.WebControls.Panel ClientsEmptyPanel;

        protected global::System.Web.UI.WebControls.TextBox SettingsCompanyNameTextBox;

        protected global::System.Web.UI.WebControls.TextBox SettingsNewRoleTextBox;

        protected global::System.Web.UI.WebControls.Button AddSettingsRoleButton;

        protected global::System.Web.UI.WebControls.Repeater SettingsRolesRepeater;

        protected global::System.Web.UI.WebControls.TextBox SettingsNewTripStatusTextBox;

        protected global::System.Web.UI.WebControls.Button AddSettingsTripStatusButton;

        protected global::System.Web.UI.WebControls.Repeater SettingsTripStatusesRepeater;

        protected global::System.Web.UI.WebControls.DropDownList SettingsDefaultTripStatusDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList SettingsDefaultTabDropDownList;

        protected global::System.Web.UI.WebControls.CheckBox SettingsRequireUniqueTripNumbersCheckBox;

        protected global::System.Web.UI.WebControls.CheckBox SettingsValidatePrepaymentCheckBox;

        protected global::System.Web.UI.WebControls.FileUpload SettingsLogoUpload;

        protected global::System.Web.UI.WebControls.TextBox SettingsAllowedDocumentExtensionsTextBox;

        protected global::System.Web.UI.WebControls.TextBox SettingsAllowedLogoExtensionsTextBox;

        protected global::System.Web.UI.WebControls.Button SaveSettingsButton;

    protected global::System.Web.UI.WebControls.FileUpload SettingsImportExcelUpload;

    protected global::System.Web.UI.WebControls.Button ImportCrmExcelButton;

    protected global::System.Web.UI.WebControls.Button ExportCrmExcelTemplateButton;

    protected global::System.Web.UI.WebControls.Panel CrmExcelImportReportPanel;

    protected global::System.Web.UI.WebControls.Literal CrmExcelImportReportLiteral;

    protected global::System.Web.UI.WebControls.FileUpload SettingsImportJsonUpload;

    protected global::System.Web.UI.WebControls.Button ImportSettingsButton;

    protected global::System.Web.UI.WebControls.Button ExportSettingsButton;

    protected global::System.Web.UI.WebControls.DropDownList SettingsHomeContentLanguageDropDownList;

    protected global::System.Web.UI.WebControls.TextBox SettingsHomeContactAddressTextBox;

    protected global::System.Web.UI.WebControls.TextBox SettingsHomeContactPhoneTextBox;

    protected global::System.Web.UI.WebControls.TextBox SettingsHomeContactHoursTextBox;

    protected global::System.Web.UI.WebControls.TextBox SettingsHomeContactWhatsAppUrlTextBox;

    protected global::System.Web.UI.WebControls.TextBox SettingsNewHomePartnerTextBox;

    protected global::System.Web.UI.WebControls.Button AddSettingsHomePartnerButton;

    protected global::System.Web.UI.WebControls.Repeater SettingsHomePartnersRepeater;

    protected global::System.Web.UI.WebControls.TextBox SettingsNewHomeReviewQuoteTextBox;

    protected global::System.Web.UI.WebControls.TextBox SettingsNewHomeReviewAuthorTextBox;

    protected global::System.Web.UI.WebControls.Button AddSettingsHomeReviewButton;

    protected global::System.Web.UI.WebControls.Repeater SettingsHomeReviewsRepeater;

    protected global::System.Web.UI.WebControls.Literal DashboardInquiryFilterNoticeLiteral;

    protected global::System.Web.UI.WebControls.TextBox SettingsLeadFilterPhoneTextBox;

    protected global::System.Web.UI.WebControls.TextBox SettingsLeadFilterMessengerTextBox;

    protected global::System.Web.UI.WebControls.TextBox SettingsLeadFilterDirectionTextBox;

    protected global::System.Web.UI.WebControls.DropDownList SettingsLeadFilterCargoTypeDropDownList;

    protected global::System.Web.UI.WebControls.TextBox SettingsLeadFilterCommentTextBox;

    protected global::System.Web.UI.WebControls.HiddenField SettingsLeadFilterPanelStateHiddenField;

    protected global::System.Web.UI.WebControls.Literal SettingsLeadFilterSummaryLiteral;

    protected global::System.Web.UI.WebControls.Button ApplySettingsLeadFiltersButton;

    protected global::System.Web.UI.WebControls.Button ResetSettingsLeadFiltersButton;

    protected global::System.Web.UI.WebControls.HiddenField InquiriesSelectedIdsHiddenField;

    protected global::System.Web.UI.WebControls.DropDownList SettingsInquiryBulkStatusDropDownList;

    protected global::System.Web.UI.WebControls.Button SettingsInquiryBulkStatusButton;

    protected global::System.Web.UI.WebControls.Repeater SettingsInquiryListRepeater;

    protected global::System.Web.UI.WebControls.HiddenField SettingsSelectedInquiryIdHiddenField;

    protected global::System.Web.UI.WebControls.Panel SettingsInquiryDetailPanel;

    protected global::System.Web.UI.WebControls.LinkButton CloseSettingsInquiryDetailButton;

    protected global::System.Web.UI.WebControls.Repeater SettingsRecentInquiriesRepeater;

    protected global::System.Web.UI.WebControls.Panel SettingsRecentInquiriesEmptyPanel;

        protected global::System.Web.UI.WebControls.Literal SettingsCurrentCompanyNameLiteral;

        protected global::System.Web.UI.WebControls.Panel SettingsCurrentLogoPanel;

        protected global::System.Web.UI.HtmlControls.HtmlAnchor SettingsCurrentLogoLink;

        protected global::System.Web.UI.WebControls.Image SettingsLogoPreviewImage;

        protected global::System.Web.UI.WebControls.Panel SettingsNoLogoPanel;
    }
}
