//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLC_EXPRESS
{


    public partial class orders
    {

        protected global::System.Web.UI.WebControls.Panel PageAlertPanel;

        protected global::System.Web.UI.WebControls.Literal PageAlertLiteral;

        protected global::System.Web.UI.WebControls.Literal TripsFormTitleLiteral;

        protected global::System.Web.UI.WebControls.HiddenField TripsEditingIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox TripsNumberTextBox;

        protected global::System.Web.UI.WebControls.DropDownList TripsClientDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList TripsStatusDropDownList;

        protected global::System.Web.UI.WebControls.TextBox TripsCountryTextBox;

        protected global::System.Web.UI.WebControls.DropDownList TripsVehicleDropDownList;

        protected global::System.Web.UI.WebControls.DropDownList TripsDriverDropDownList;

        protected global::System.Web.UI.WebControls.TextBox TripsStartDateTextBox;

        protected global::System.Web.UI.WebControls.TextBox TripsEndDateTextBox;

        protected global::System.Web.UI.WebControls.TextBox TripsFreightTextBox;

        protected global::System.Web.UI.WebControls.TextBox TripsPrepaymentTextBox;

        protected global::System.Web.UI.WebControls.Button AddTripButton;

        protected global::System.Web.UI.WebControls.Button TripsCancelEditButton;

        protected global::System.Web.UI.WebControls.Repeater TripsRepeater;

        protected global::System.Web.UI.WebControls.Panel TripsEmptyPanel;

        protected global::System.Web.UI.WebControls.Literal DriversFormTitleLiteral;

        protected global::System.Web.UI.WebControls.HiddenField DriversEditingIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox DriversFullNameTextBox;

        protected global::System.Web.UI.WebControls.TextBox DriversBirthDateTextBox;

        protected global::System.Web.UI.WebControls.TextBox DriversPhoneTextBox;

        protected global::System.Web.UI.WebControls.TextBox DriversAddressTextBox;

        protected global::System.Web.UI.WebControls.FileUpload DriversPassportUpload;

        protected global::System.Web.UI.WebControls.FileUpload DriversLicenseUpload;

        protected global::System.Web.UI.WebControls.Button AddDriverButton;

        protected global::System.Web.UI.WebControls.Button DriversCancelEditButton;

        protected global::System.Web.UI.WebControls.Repeater DriversRepeater;

        protected global::System.Web.UI.WebControls.Panel DriversEmptyPanel;

        protected global::System.Web.UI.WebControls.Literal FleetFormTitleLiteral;

        protected global::System.Web.UI.WebControls.HiddenField FleetEditingIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox FleetCarBrandTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetCarModelTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetLicensePlateTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetVinTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetTrailerBrandTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetTrailerModelTextBox;

        protected global::System.Web.UI.WebControls.TextBox FleetTrailerLicensePlateTextBox;

        protected global::System.Web.UI.WebControls.CheckBoxList FleetDriversCheckBoxList;

        protected global::System.Web.UI.WebControls.FileUpload FleetDocumentsUpload;

        protected global::System.Web.UI.WebControls.Button AddFleetButton;

        protected global::System.Web.UI.WebControls.Button FleetCancelEditButton;

        protected global::System.Web.UI.WebControls.Repeater FleetRepeater;

        protected global::System.Web.UI.WebControls.Panel FleetEmptyPanel;

        protected global::System.Web.UI.WebControls.Literal ClientsFormTitleLiteral;

        protected global::System.Web.UI.WebControls.HiddenField ClientsEditingIdHiddenField;

        protected global::System.Web.UI.WebControls.TextBox ClientsNameTextBox;

        protected global::System.Web.UI.WebControls.TextBox ClientsDirectionTextBox;

        protected global::System.Web.UI.WebControls.TextBox ClientsManagerTextBox;

        protected global::System.Web.UI.WebControls.TextBox ClientsPhoneTextBox;

        protected global::System.Web.UI.WebControls.TextBox ClientsEmailTextBox;

        protected global::System.Web.UI.WebControls.Button AddClientButton;

        protected global::System.Web.UI.WebControls.Button ClientsCancelEditButton;

        protected global::System.Web.UI.WebControls.Repeater ClientsRepeater;

        protected global::System.Web.UI.WebControls.Panel ClientsEmptyPanel;
    }
}
